module:
    backbone: vit_small
    pretrained: True
    num_classes: 9
    num_samples: 4
    downsample: 16
    proj_hidden_dim: 128
    proj_dim: 256

datamodule:
    root: /mnt/e/data/
##    batch_size: 208
#    batch_size: 128
#    batch_size: 104
#    batch_size: 96
#    batch_size: 64
    batch_size: 128

#    batch_size: 52
#    batch_size: 48
    num_workers: 18
    prefetch_factor: 2

trainer:
#    max_epochs: 5
    max_epochs: 20
    precision: 16
#    gpus: 2
    gpus: 1
    log_every_n_steps: 25
